spring:
  application:
    name: student-service
  jackson:
    default-property-inclusion: NON_NULL
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:mysql://localhost:3306/student_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    "[org.hibernate.SQL]": DEBUG

security:
  jwt:
    secret: "mySecretKeyForJWTTokenGenerationAndValidationMySecretKeyForJWTTokenGenerationAndValidation"
    expiration: 86400000 # 24 hours in milliseconds
    refresh-expiration: 604800000 # 7 days in milliseconds
